# DEBUG
DEBUG = True

# TIMEFORMAT
TIMEFORMAT = '%X'

# TIME
OPENTIME = '09:30:00'
CLOSETIME = '15:00:00'

# DATABASE
DATABASE_USER = 'root'
DATABASE_PASSWORD = '3345*moxiaowa'
DATABASE_NAME = 'stock'
DATABASE_SERVER = 'localhost'
DATABASE_PORT = '3306'
DATABASE_URL = 'mysql+pymysql://' + DATABASE_USER + ':' + DATABASE_PASSWORD + '@' + DATABASE_SERVER + ':' + DATABASE_PORT + '/' + DATABASE_NAME + '?charset=utf8'
